#!/bin/bash

set -o pipefail
export PATH=/bin

start() {
  hostname router

  mount -a -t proc
  mount -a -m -t devpts,devtmpfs,sysfs,tmpfs
  mount -m -r -B /run/empty /run/empty
  mkdir -m 1777 -p /run/lock /run/shm

  ln -f -n -s pts/ptmx /dev/ptmx
  ln -f -n -s /proc/self/fd /dev/fd
  ln -f -n -s fd/0 /dev/stdin
  ln -f -n -s fd/1 /dev/stdout
  ln -f -n -s fd/2 /dev/stderr

  echo timer >/sys/class/leds/white\:power/trigger

  mount -o remount,ro /
  mount -a -t nonfs

  if [[ -c /dev/watchdog ]] && exec >/dev/watchdog && wait; then
    trap 'printf V && exit' TERM
    while printf '\0'; do read -t 5; done
  fi <><(:) & disown

  nft -f /etc/filter
  sysctl -q net.ipv{4,6}.conf.all.forwarding=1

  ip link set lo up
  ip link set eth0 up
  ip link set lan up
  ip link set wan up

  ip link add name br0 type bridge
  ip link set lan master br0
  ip link set wan master br0
  ip link set br0 up

  ip address add 192.168.1.1/24 dev br0

  echo netdev >/sys/class/leds/white\:wan/trigger
  echo wwan0 >/sys/class/leds/white\:wan/device_name
  echo 1 >/sys/class/leds/white\:wan/rx
  echo 1 >/sys/class/leds/white\:wan/tx

  syslogd -k
  ssh-keygen -A && $(type -P sshd)
  dnsmasq

  if wwan /dev/wwan0mbim0 start; then
    if mbim /dev/wwan0mbim0 config | grep -q '^gateway [0-9a-f:]*$'; then
      ip address add 2001:2::1/64 dev br0
    fi
    while true; do
      while mbim /dev/wwan0mbim0 config; do read -t 30; done
      logger -p daemon.warn -t watchdog 'Restarting wwan connection'
      wwan /dev/wwan0mbim0 start
    done <><(:) >/dev/null 2>&1 & disown
  fi

  hostapd -s -B /etc/ap0.conf /etc/ap1.conf
  ip link set wlan0 type bridge_slave hairpin on mcast_to_unicast on
  ip link set wlan1 type bridge_slave hairpin on mcast_to_unicast on

  daemon await-net ntpd -p /run/ntpd.pid

  echo default-on >/sys/class/leds/white\:power/trigger

  trap 'exec "$0" stop reboot' INT
  trap 'exec "$0" stop poweroff' TERM

  ctrlaltdel soft
  while true; do read; done <><(:)
}

stop() {
  kill -TERM -1 && sleep 2 && kill -KILL -1
  if umount -a -r; then
    echo "Remounted filesystems read-only"
  else
    sync && echo "Flushed filesystem writes"
  fi
  exec stop "$@"
}

"${@:-start}"
