#!/bin/bash

set -o pipefail
export PATH=/bin

start() {
  hostname gl-ap1300

  mount -a -t proc
  mount -a -m -t devpts,devtmpfs,sysfs,tmpfs
  mount -m -r -B /run/empty /run/empty
  mkdir -m 1777 -p /run/lock /run/shm

  ln -f -n -s pts/ptmx /dev/ptmx
  ln -f -n -s /proc/self/fd /dev/fd
  ln -f -n -s fd/0 /dev/stdin
  ln -f -n -s fd/1 /dev/stdout
  ln -f -n -s fd/2 /dev/stderr

  echo timer >/sys/class/leds/green\:power/trigger

  mount -o remount,rw /
  mount -a -t nonfs

  if [[ -c /dev/watchdog ]] && exec >/dev/watchdog; then
    trap 'printf V && exit' TERM
    while printf '\0'; do read -t 5; done
  fi <><(:) & disown

  ip link set lo up
  ip link set eth0 up
  ip link set lan up
  ip link set wan up

  ip link add name br0 type bridge
  ip link set lan master br0
  ip link set wan master br0
  ip link set br0 up

  ip address add 172.16.0.1/24 dev br0

  syslogd -k
  ssh-keygen -A && $(type -P sshd)

  echo default-on >/sys/class/leds/green\:power/trigger
}

listen() {
  if [[ ! -p /dev/initctl ]]; then
    rm -f /dev/initctl
    mkfifo -m 0600 /dev/initctl
  fi

  while read -d '' -r MESSAGE; do
    case "$MESSAGE" in
      halt | poweroff | reboot)
        exec "$0" stop "$MESSAGE"
        ;;
    esac
  done <>/dev/initctl
}

stop() {
  kill -TERM -1 && sleep 2 && kill -KILL -1
  if umount -a -r; then
    echo "Remounted filesystems read-only"
  else
    sync && echo "Flushed filesystem writes"
  fi
  exec stop "$@"
}

trap listen EXIT
"${@:-start}"
