#!/bin/bash

set -o pipefail
shopt -s dotglob extglob globstar nullglob
export PATH=/bin

hostname gl-ap1300

mount -a -n -t proc
mount -a -n -t devtmpfs,sysfs,tmpfs
mkdir -p /dev/pts && mount -a -n -t devpts
mkdir -m 0755 -p /run/empty && mount -r -B /run/empty /run/empty
mkdir -m 1777 -p /run/lock /run/shm

ln -f -n -s /proc/self/fd /dev/fd
ln -f -n -s pts/ptmx /dev/ptmx
ln -f -n -s fd/0 /dev/stdin
ln -f -n -s fd/1 /dev/stdout
ln -f -n -s fd/2 /dev/stderr

mount -o remount,rw /
mount -a -t nonfs

if [[ -c /dev/watchdog ]] && exec >/dev/watchdog; then
  trap 'printf V && exit' TERM
  while printf '\0'; do read -t 5; done
fi <><(:) & disown

ip link set lo up
ip link set eth0 up
ip link set lan up
ip link set wan up

ip link add name br0 type bridge
ip link set lan master br0
ip link set wan master br0
ip link set br0 up

ip address add 172.16.0.1/24 dev br0

syslogd -k
ssh-keygen -A && $(type -P sshd)
echo heartbeat >/sys/class/leds/green\:wan/trigger

mkfifo -m 0600 /dev/initctl
while read -d '' -r MESSAGE; do
  [[ $MESSAGE == @(halt|poweroff|reboot) ]] && break
done <>/dev/initctl

kill -TERM -1 && sleep 2 && kill -KILL -1
umount -a -d -r
sync && exec stop "$MESSAGE"
